== Issue #4
[.subheading]
Managing Templates

=== Angular Template Resolution

[source,html]
----
<div ng-include=" 'my-template.html' "></div>
----

If *my-template.html* isn't in Angular's template cache then an HTTP GET request is done for *my-template.html*

[NOTE.speaker]
--
* Templates are usually used for HTML used by controllers and directives
* You want to avoid the performance hit of an extra HTTP request
* You want to make absolutely sure javascript and templates are in sync 
--

=== Adding to The Template Cache

[source,html,role='fragment']
.Template in a script tag
----
<script type="text/ng-template" id="my-template.html">
  <h1>My template</h1>
</script>
----

[source,javascript,role='fragment']
.Add directly to $templateCache in a run block
----
myApp.run(function($templateCache) {
  $templateCache.put('my-template.html', '<h1>My template</h1>');
});
----

=== Solutions

[.step]
* Just use plain html template files [.fragment]#icon:frown-o[]#
* Add to $templateCache via a script tag or run block [.fragment]#icon:frown-o[]#
* Use the Angular Templates Asset Pipeline plugin [.fragment]#icon:smile-o[]#


=== Angular Template Asset Pipeline Plugin

[source,gradle,role="fragment"]
----
buildscript {
  dependencies {
    classpath 'com.craigburke.angular:angular-template-asset-pipeline:2.2.1'
  }
}
----

=== Example

[source,html,role='fragment']
.file located at *src/assets/js/my-app/users/list.tpl.html*
----
<p>Hello</p>
----

[source,javascript,role='fragment']
.Becomes something like this:
----
angular.module('myApp.users').run(function($templateCache) {
  $templateCache.put('/my-app/users/list.html', '<p>Hello</p>');
});
----

=== Example #2

[source,gradle,role='fragment']
.Set *moduleNameBase* property
----
assets {
  configOptions = [
    angular : [ moduleNameBase: 'myApp' ]
  ]
}
----

[source,html,role='fragment']
.file located at *src/assets/js/users/list.tpl.html*
----
<p>Hello</p>
----

[source,javascript,role='fragment']
.Becomes something like this:
----
angular.module('myApp.users').run(function($templateCache) {
  $templateCache.put('/users/list.html', '<p>Hello</p>');
});
----


